import localFont from "next/font/local";
import "./globals.css";
import { AppKitProvider } from "../context/connection";
// import "../context/connection";
// import { cookieToInitialState } from 'ethers'
 
const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	// const initialState = cookieToInitialState(config, headers().get('cookie'))

	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<AppKitProvider>{children}</AppKitProvider>
			</body>
		</html>
	);
}
